version: "3.7"

x-service: &default-service
    logging:
        driver: json-file
        options:
            max-size: "10m"
            max-file: "5"
    init: true
    restart: unless-stopped

x-environment: &default-environment
    TZ: Asia/Tokyo
    UNIFI_HTTP_PORT: 8081
    BIND_PRIV: 'false'
    RUNAS_UID0: 'false'

x-network-host: &custom-network-host
    network_mode: "host"

services:
    unifi:
        container_name: unifi
        <<: *default-service
        <<: *custom-network-host
        image: jacobalberty/unifi:latest
#        ports:
#            - "3478:3478/udp" # STUN
#            - "6789:6789/tcp" # Speed test
#            - "8080:8080/tcp" # Device/ controller comm.
#            - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
#            - "8880:8880/tcp" # HTTP portal redirection
#            - "8843:8843/tcp" # HTTPS portal redirection
#            - "10001:10001/udp" # AP discovery
        deploy:
             resources:
                  limits:
                       memory: 1G
                  reservations:
                       memory: 256M
        volumes:
             - ./unifi:/unifi
        environment:
            <<: *default-environment
